"DOTAUnits"
{
	"lily"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/lily_white/lily_white.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Furion_Treant"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_lily_01"
		"Ability4"					"thtd_lily_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"0"
		"AttackRange"				"0"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"100"
		"StatusManaRegen"			"1.5"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"nazrin"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/nazrin/nazrin.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Nazrin"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_nazrin_01"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"4"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1400"
		"AttackRange"				"1400"
		"ProjectileModel"			"particles/heroes/nazrin/nazrin_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"minoriko"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/minoriko/minoriko.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_minoriko_01"
		"Ability4"					"thtd_minoriko_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_star_up_speed"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"0"
		"AttackRange"				"0"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"mugiyousei"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/mugiyousei/mugiyousei.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Venomancer"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_mugiyousei_01"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.7"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_viper/viper_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	  
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"shanghainingyou"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/shanghainingyou/shanghainingyou.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Shanghai"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_shanghainingyou_01"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"1100"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"hourainingyou"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/hourainingyou/hourainingyou.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Sniper"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_hourainingyou_01"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"1100"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	  
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"hanadayousei"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/hanadayousei/hanadayousei.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Puck"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_puck.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_hanadayousei_01"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/econ/items/keeper_of_the_light/kotl_weapon_arcane_staff/keeper_base_attack_arcane_staff.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	  
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}
	"maidyousei"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/maidyousei/maidyousei.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Luna"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_luna.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"luna_moon_glaive"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_luna/luna_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	  
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}
	"cirno"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/cirno/cirno.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Cirno"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_cirno_01"
		"Ability4"					"thtd_cirno_02"
		"Ability5"					"thtd_cirno_03"
		"Ability6"					"thtd_cirno_04"
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"


		"AbilityLayout"				"8"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/neutral_fx/black_dragon_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"90"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"letty"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/letty/letty.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Crystal"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_letty_01"
		"Ability4"					"thtd_letty_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_decrease_magic_armor_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_lich/lich_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"8.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"kogasa"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/kogasa/kogasa.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Kogasa"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_kogasa_01"
		"Ability4"					"thtd_kogasa_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_decrease_armor_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.9"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"8.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"lyrica"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/lyrica_prismriver/lyrica.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Lyrica"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_lyrica_01"
		"Ability4"					"thtd_lyrica_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"900"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"6.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"lunasa"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/lunasa_prismriver/lunasa.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Lunasa"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_lunasa_01"
		"Ability4"					"thtd_lunasa_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"900"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"6.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"merlin"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/merlin_prismriver/merlin.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Merlin"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_merlin_01"
		"Ability4"					"thtd_merlin_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"900"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"6.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"rumia"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/rumia/rumia.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_ShadowDemon"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_shadow_demon.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_rumia_01"
		"Ability4"					"thtd_rumia_02"
		"Ability5"					"thtd_rumia_03"
		"Ability6"					"thtd_rumia_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"
		"ProjectileModel"			"particles/econ/items/shadow_fiend/sf_desolation/sf_base_attack_desolation.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"satori"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/satori/satori.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Bane"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_satori_01"
		"Ability4"					"thtd_satori_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_dark_willow/dark_willow_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"20"
		"StatusManaRegen"			"3.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"iku"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/iku/iku.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_StormSpirit"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_iku_01"
		"Ability4"					"thtd_iku_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"600"
		"AttackRange"				"600"
		"ProjectileModel"			"particles/units/heroes/hero_disruptor/disruptor_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"4"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"mystia"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/mystia/mystia.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_BloodSeeker"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_mystia_01"
		"Ability4"					"thtd_mystia_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"5"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"marisa"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/marisa/marisa.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Marisa"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_marisa_01"
		"Ability4"					"thtd_marisa_02"
		"Ability5"					"thtd_marisa_03"
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"750"
		"AttackRange"				"750"
		"ProjectileModel"			"particles/heroes/thtd_marisa/ability_marisa_02_normal.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"80"
		"StatusManaRegen"			"2.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}
	"tenshi"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/tenshi/tenshi.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Axe"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_axe.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_tenshi_01"
		"Ability4"					"thtd_tenshi_02"
		"Ability5"					"thtd_tenshi_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"750"
		"AttackRange"				"750"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"5.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"patchouli"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/patchouli/patchouli.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Invoker"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_patchouli_01"
		"Ability4"					"thtd_patchouli_02"
		"Ability5"					"thtd_patchouli_03"
		"Ability6"					"thtd_patchouli_04"
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_oracle/oracle_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"80"
		"StatusManaRegen"			"8.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"reisen"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/reisen/reisen.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Reisen"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_reisen_01"
		"Ability4"					"thtd_reisen_02"
		"Ability5"					"thtd_reisen_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"
		"ProjectileModel"			"particles/heroes/reisen/ability_reisen_base_attack.vpcf"
		"ProjectileSpeed"			"3000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"80"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"yuyuko"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/yuyuko/yuyuko.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Necrolyte"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_yuyuko_01"
		"Ability4"					"thtd_yuyuko_02"
		"Ability5"					"thtd_yuyuko_03"
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_necrolyte/necrolyte_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"50"
		"StatusManaRegen"			"6.5"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"youmu"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/youmu/youmu.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.1"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Youmu"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_youmu_01"
		"Ability4"					"thtd_youmu_02"
		"Ability5"					"thtd_youmu_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"20"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"rin"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/rin/rin.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Lina"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_lina.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_rin_01"
		"Ability4"					"thtd_rin_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"utsuho"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/utsuho/utsuho.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Utsuho"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_utsuho_01"
		"Ability4"					"thtd_utsuho_02"
		"Ability5"					"thtd_utsuho_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.7"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1600"
		"AttackRange"				"1600"
		"ProjectileModel"			"particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"reimu"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/reimu/reimu.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Reimu"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_reimu_01"
		"Ability4"					"thtd_reimu_02"
		"Ability5"					"thtd_reimu_03"
		"Ability6"					"thtd_reimu_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/heroes/thtd_reimu/ability_reimu_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"6.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"daiyousei"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/daiyousei/daiyousei.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Wisp"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_daiyousei_01"
		"Ability4"					"thtd_daiyousei_02"
		"Ability5"					"thtd_daiyousei_03"
		"Ability6"					"thtd_daiyousei_04"
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/econ/items/keeper_of_the_light/kotl_weapon_arcane_staff/keeper_base_attack_arcane_staff.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"20"
		"StatusManaRegen"			"1.5"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"remilia"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/remilia/remilia.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Nevermore"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_remilia_01"
		"Ability4"					"thtd_remilia_02"
		"Ability5"					"thtd_remilia_03"
		"Ability6"					"thtd_remilia_04"
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/econ/items/shadow_fiend/sf_desolation/sf_base_attack_desolation_fire_arcana.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"5"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"flandre"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/flandre/flandre.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_DoomBringer"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_doombringer.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_flandre_01"
		"Ability4"					"thtd_flandre_02"
		"Ability5"					"thtd_flandre_03"
		"Ability6"					"thtd_flandre_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"sakuya"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/sakuya/sakuya.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_QueenOfPain"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_sakuya_01"
		"Ability4"					"thtd_sakuya_02"
		"Ability5"					"thtd_sakuya_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_queenofpain/queen_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"4"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"koishi"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/koishi/koishi.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Leshrac"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_koishi_01"
		"Ability4"					"thtd_koishi_02"
		"Ability5"					"thtd_koishi_03"
		"Ability6"					"thtd_koishi_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/econ/items/leshrac/leshrac_tormented_staff/leshrac_base_attack_tormented.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"2.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"koakuma"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/koakuma/koakuma.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Lina"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_lina.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_koakuma_01"
		"Ability4"					"thtd_koakuma_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"3.5"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"meirin"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/meirin/meirin.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_meirin_01"
		"Ability4"					"thtd_meirin_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"yuuka"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/new_touhou_model/yuuka/yuuka.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Tiny"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_yuuka_01"
		"Ability4"					"thtd_yuuka_02"
		"Ability5"					"thtd_yuuka_03"
		"Ability6"					"thtd_yuuka_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"30"
		"StatusManaRegen"			"2"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
	
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"yukari"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/yukari/yukari.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_ObsidianDestroyer"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_yukari_01"
		"Ability4"					"thtd_yukari_02"
		"Ability5"					"thtd_yukari_03"
		"Ability6"					"thtd_yukari_04"
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"3.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"ran"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/ran/ran.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Puck"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_puck.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_ran_01"
		"Ability4"					"thtd_ran_02"
		"Ability5"					"thtd_ran_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/econ/items/puck/puck_alliance_set/puck_base_attack_aproset.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"3.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"chen"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/chen/chen.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Chen"
		"GameSoundsFile"			"soundevents/game_sounds/thdots_tower_attack_sounds.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_chen_01"
		"Ability4"					"thtd_chen_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"1"
		"StatusManaRegen"			"1"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"eirin"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/eirin/eirin.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"IsAncient"					"1"
		"SoundSet"					"Hero_Mirana"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_eirin_01"
		"Ability4"					"thtd_eirin_02"
		"Ability5"					"thtd_eirin_03"
		"Ability6"					"thtd_eirin_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"900"
		"ProjectileModel"			"particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"100"
		"StatusManaRegen"			"10.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"mokou"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/mokou/mokou.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"
		"SoundSet"					"Hero_ChaosKnight"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_mokou_01"
		"Ability4"					"thtd_mokou_02"
		"Ability5"					"thtd_mokou_03"
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"kaguya"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/kaguya/kaguya.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_kaguya_01"
		"Ability4"					"thtd_kaguya_02"
		"Ability5"					"thtd_kaguya_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/econ/items/puck/puck_alliance_set/puck_base_attack_aproset.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"90"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"aya"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/aya/aya.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_aya_01"
		"Ability4"					"thtd_aya_02"
		"Ability5"					"thtd_aya_03"
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.25"
		"AttackAnimationPoint"		"0.25"
		"AttackAcquisitionRange"	"1200"
		"AttackRange"				"1200"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"hatate"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/hatate/hatate.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.8"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_hatate_01"
		"Ability4"					"thtd_hatate_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.3"
		"AttackAnimationPoint"		"0.3"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"20"
		"StatusManaRegen"			"3"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"momiji"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/momiji/momiji.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.8"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_momiji_01"
		"Ability4"					"thtd_momiji_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"sanae"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/sanae/sanae.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_sanae_01"
		"Ability4"					"thtd_sanae_02"
		"Ability5"					"thtd_sanae_03"
		"Ability6"					"thtd_sanae_04"
		"Ability7"					"ability_common_mana_regen_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_lion/lion_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"kanako"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/kanako/kanako.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_kanako_01"
		"Ability4"					"thtd_kanako_02"
		"Ability5"					"thtd_kanako_03"
		"Ability6"					"thtd_kanako_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_zuus/zuus_base_attack.vpcf"
		"ProjectileSpeed"			"3000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"
		"VisionNighttimeRange"		"1200"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"suwako"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/suwako/suwako.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.8"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_suwako_01"
		"Ability4"					"thtd_suwako_02"
		"Ability5"					"thtd_suwako_03"
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"minamitsu"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/minamitsu/minamitsu.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.2"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_minamitsu_01"
		"Ability4"					"thtd_minamitsu_02"
		"Ability5"					"thtd_minamitsu_03"
		"Ability6"					"thtd_minamitsu_04"
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"nue"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/nue/nue.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_nue_01"
		"Ability4"					"thtd_nue_02"
		"Ability5"					"thtd_nue_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"sizuha"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/sizuha/sizuha.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.9"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_sizuha_01"
		"Ability4"					"thtd_sizuha_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_star_up_speed"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"0"
		"AttackRange"				"0"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"byakuren"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/byakuren/byakuren.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_byakuren_01"
		"Ability4"					"thtd_byakuren_02"
		"Ability5"					"thtd_byakuren_03"
		"Ability6"					"thtd_byakuren_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.2"
		"AttackAcquisitionRange"	"1200"
		"AttackRange"				"1200"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"toramaru"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/toramarushou/toramarushou.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_toramaru_01"
		"Ability4"					"thtd_toramaru_02"
		"Ability5"					"thtd_toramaru_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1200"
		"AttackRange"				"1200"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"shinki"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/shinki/shinki.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.2"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_shinki_01"
		"Ability4"					"thtd_shinki_02"
		"Ability5"					"thtd_shinki_03"
		"Ability6"					"thtd_shinki_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/heroes/thtd_reimu/ability_reimu_base_attack.vpcf"
		"ProjectileSpeed"			"1400"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"60"
		"StatusManaRegen"			"6.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"soga"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/soga/soga.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_soga_01"
		"Ability4"					"thtd_soga_02"
		"Ability5"					"thtd_soga_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"800"
		"AttackRange"				"800"
		"ProjectileModel"			"particles/units/heroes/hero_arc_warden/arc_warden_base_attack.vpcf"
		"ProjectileSpeed"			"2000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"50"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"
		"VisionNighttimeRange"		"1200"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"futo"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/futo/futo.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_futo_01"
		"Ability4"					"thtd_futo_02"
		"Ability5"					"thtd_futo_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"1200"
		"AttackRange"				"1200"
		"ProjectileModel"			"particles/heroes/thtd_futo/ability_futo_base_attack_6.vpcf"
		"ProjectileSpeed"			"1500"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"50"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"
		"VisionNighttimeRange"		"1200"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"miko"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/miko/miko.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_miko_01"
		"Ability4"					"thtd_miko_02"
		"Ability5"					"thtd_miko_03"
		"Ability6"					"thtd_miko_04"
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.2"
		"AttackAcquisitionRange"	"1200"
		"AttackRange"				"1200"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"yoshika"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/yoshika/yoshika.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.8"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_yoshika_01"
		"Ability4"					"thtd_yoshika_02"
		"Ability5"					""
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.2"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"seiga"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/seiga/seiga.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.8"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_seiga_01"
		"Ability4"					"thtd_seiga_02"
		"Ability5"					"thtd_seiga_03"
		"Ability6"					""
		"Ability7"					"ability_common_power_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"
		"ProjectileModel"			"particles/units/heroes/hero_leshrac/leshrac_base_attack.vpcf"
		"ProjectileSpeed"			"1500"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"50"
		"StatusManaRegen"			"4.0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"
		"VisionNighttimeRange"		"1200"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}

	"keine"
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/thd_hero/keine/keine.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"1"
		"ModelScale" 				"0.8"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_touhoutd_star_up"
		"Ability2"					"ability_touhoutd_exp_up"
		"Ability3"					"thtd_keine_01"
		"Ability4"					"thtd_keine_02"
		"Ability5"					"thtd_keine_03"
		"Ability6"					""
		"Ability7"					"ability_common_attack_speed_buff"
		"Ability8"					"ability_common_attack_buff"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2"
		"AttackDamageMax"			"2"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.55"
		"AttackAcquisitionRange"	"1000"
		"AttackRange"				"1000"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"128"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"100"	
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"	 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		"ConsideredHero"			"1"
	}
}